# -*- coding: utf-8 -*-
"""Home.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18_dY1P9hGCeYmmFSHgON1uX3Nva_TlG2
"""

import streamlit as st

headline = 'The Art of War '

st.set_page_config(
    page_title='The Art of War : A Comprehensive Visualization of World Military Strength',
    page_icon='',
    layout='wide',
    initial_sidebar_state='expanded',
)

st.markdown(
    """
    <style>
    .stApp {
        background-image: url('https://ssbcrackexams.com/wp-content/uploads/2024/06/Indian-Army.jpg');
        background-attachment: fixed;
        background-size: cover;
    }
    </style>
    """,
    unsafe_allow_html=True,
)

st.title(headline)
st.markdown("""
""", unsafe_allow_html=False)

# Adding a brief introduction about the project in bold
st.markdown("""
**An interactive data visualization that unveils the hidden dynamics of global defense. By seamlessly integrating trade data, missile inventories, military manpower, defense budgets, and power indexes.""", unsafe_allow_html=False)

# TODO: Homepage components
st.markdown("""
**Join us as we decode complex defense data into an engaging visual story of strength, strategy, and global influence.**
""", unsafe_allow_html=False)